version: '3'
services:

  postgresql:
    image: docker.io/bitnami/postgresql:13
    container_name: postgresql
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    networks:
      - keycloak-network

  keycloak:
    image: docker.io/bitnami/keycloak:${SOFTWARE_VERSION_TAG}
    container_name: keycloak
    restart: always
    env_file:
      - .env
    ports:
      - '172.17.0.1:8080:8080'
    environment:
      - KEYCLOAK_DATABASE_NAME=$POSTGRESQL_DATABASE
      - KEYCLOAK_DATABASE_USER=$POSTGRESQL_USERNAME
      - KEYCLOAK_DATABASE_PASSWORD=$POSTGRESQL_PASSWORD
      - KEYCLOAK_DATABASE_SCHEMA=public
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - postgresql
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge